FROM openjdk
MAINTAINER Ramiro Vargas <ramiro.vargassalas@gmail.com>
ADD target/containerized-bills-0.0.1-SNAPSHOT.jar containerized-bills.jar
ENTRYPOINT ["java", "-jar", "/containerized-bills.jar"]
EXPOSE 2222
