FROM openjdk
MAINTAINER Ramiro Vargas <ramiro.vargassalas@gmail.com>
ADD target/containerized-logistic-0.0.1-SNAPSHOT.jar containerized-logistic.jar
ENTRYPOINT ["java", "-jar", "/containerized-logistic.jar"]
EXPOSE 2222
